fix: chmod on k0sctl after downloading

diff --git a/bin/play b/bin/play
--- a/bin/play
+++ b/bin/play
@@ -1,8 +1,12 @@
 #! /usr/bin/env bash
 
-command -v k0sctl > /dev/null || (
-    echo "k0sctl not found, installing..." && \
-    wget -Oq /usr/local/bin/k0sctl https://github.com/k0sproject/k0sctl/releases/latest/download/k0sctl-darwin-x64 && \
-    echo "k0sctl downloaded"
-    )
+BINARY_PATH="$HOME/.local/bin/k0sctl"
+
+command -v k0sctl >/dev/null || (
+  echo "k0sctl not found, installing..." &&
+    wget -O $BINARY_PATH -q https://github.com/k0sproject/k0sctl/releases/latest/download/k0sctl-darwin-x64 &&
+    chmod +x $BINARY_PATH
+  echo "k0sctl downloaded"
+)
+
 k0sctl apply --disable-telemetry
